name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: false

    - name: Compile and Build Code
      if: contains(github.repository, 'java')
      run: |
        ./gradlew build
      continue-on-error: false

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} .
      continue-on-error: false

    - name: Push to Google Artifact Registry
      run: |
        echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}
      continue-on-error: false

    - name: Container Image Scan
      run: |
        gcloud artifacts docker images scan gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} --format=get(severity)
      continue-on-error: false

    - name: Create Helm Package
      run: |
        helm package .
      continue-on-error: false

    - name: Deployment Confirmation
      run: |
        read -p "Do you want to continue with deployment? (yes/no) " choice
        if [[ $choice != "yes" ]]; then
          echo "Deployment aborted."
          exit 1
        fi

    - name: Deploy to Google Kubernetes Engine
      run: |
        gcloud container clusters get-credentials n-test --zone us-central1-c --project ${{ secrets.GCP_PROJECT_ID }}
        helm upgrade --install my-app ./my-app --namespace default --set image.tag=${{ github.sha }}
